export const RANKED_SOLO_QUEUE_ID = 420;
export const RANKED_FLEX_QUEUE_ID = 440;
export const RANKED_QUEUE_IDS = [RANKED_SOLO_QUEUE_ID, RANKED_FLEX_QUEUE_ID] as const;

/** @deprecated */
export const NORMAL_BLIND_QUEUE_ID = 430;
export const QUICKPLAY_QUEUE_ID = 490;
export const NORMAL_DRAFT_QUEUE_ID = 400;
export const ARAM_QUEUE_ID = 450;

export const CLASH_QUEUE_ID = 700;

export const ONE_FOR_ALL_QUEUE_ID = 1020;

export const LOL_QUEUE_IDS = [RANKED_SOLO_QUEUE_ID, RANKED_FLEX_QUEUE_ID, NORMAL_BLIND_QUEUE_ID, QUICKPLAY_QUEUE_ID, NORMAL_DRAFT_QUEUE_ID, ARAM_QUEUE_ID, CLASH_QUEUE_ID, ONE_FOR_ALL_QUEUE_ID] as const;

export const TFT_NORMAL_QUEUE_ID = 1090;
export const TFT_RANKED_QUEUE_ID = 1100;
export const TFT_DOUBLE_UP_QUEUE_ID = 1160;
export const TFT_HYPER_ROLL_QUEUE_ID = 1130;

export const TFT_QUEUE_IDS = [TFT_NORMAL_QUEUE_ID, TFT_RANKED_QUEUE_ID, TFT_DOUBLE_UP_QUEUE_ID, TFT_HYPER_ROLL_QUEUE_ID] as const;